version: '3.7'
services:
    app:
        build: .
        container_name: apits
        volumes:
          - ./:/usr/share/nginx/html
        expose:
          - ${PORT_HTML}
          - ${PORT}
        ports:
          - ${PORT_HTML}:80
          - ${PORT}:3000
