version: '3.7'
services:
    app:
        build: .
        container_name: apits
        volumes:
          - ./:/usr/share/nginx/html
        expose:
          - 80
          - 3000
        ports:
          - 80:80
          - 3000:3000
